import { COLORS } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.primary,
    position: "absolute",
    paddingHorizontal: 20,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  scrollContent: {
    paddingBottom: 24,
    flexGrow: 1,
  },
  header: {
    width: "100%",
  },
  containerHealthWarning: {
    width: "100%",
    height: "auto",
    backgroundColor: COLORS.red3rd,
    borderColor: COLORS.red,
    borderWidth: 1,
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginVertical: 15,
  },
  descHealthWarning: {
    color: COLORS.black,
    fontFamily: "Inter-Regular",
    fontSize: 14,
    paddingBottom: 10,
  },
  titleHealth: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  containerDigit: {
    flexDirection: "row",
    gap: 20,
    paddingVertical: 10,
    alignItems: "center",
  },
  titleDigitBio: {
    color: COLORS.black,
    fontFamily: "Inter-SemiBold",
    fontSize: 16,
  },
  warningCard: {
    width: "100%",
    backgroundColor: COLORS.red4th,
    borderColor: COLORS.red2nd,
    borderWidth: 1,
    borderRadius: 10,
    padding: 16,
    marginVertical: 5,
  },
  goodCard: {
    width: "100%",
    backgroundColor: COLORS.secondary4th,
    borderColor: COLORS.secondary,
    borderWidth: 1,
    borderRadius: 10,
    padding: 16,
    marginTop: 10,
  },
  warningHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 20,
  },
  warningText: {
    gap: 1,
  },
  warningIcon: {
    width: 35,
    height: 35,
  },
  warningTitle: {
    fontFamily: "Inter-SemiBold",
    fontSize: 16,
    color: COLORS.black,
  },
  warningStatus: {
    fontFamily: "Inter-Regular",
    fontSize: 14,
    color: COLORS.red,
  },
  goodStatus: {
    fontFamily: "Inter-Regular",
    fontSize: 13,
    color: COLORS.tosca,
  },
  warningBody: {
    fontFamily: "Inter-Regular",
    fontSize: 14,
    color: "#000",
    marginBottom: 12,
  },
  warningFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  warningRisk: {
    fontFamily: "Inter-Regular",
    fontSize: 14,
    color: COLORS.black,
  },
  warningBadge: {
    borderWidth: 1,
    borderColor: COLORS.red,
    paddingVertical: 10,
    paddingHorizontal: 40,
    borderRadius: 6,
  },
  warningBadgeText: {
    color: "#FF4D4F",
    fontFamily: "Inter-SemiBold",
    fontSize: 13,
  },

  // health statistcs
  statsCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    marginTop: 12,
  },
  statsHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  statsIcon: {
    width: 35,
    height: 35,
    marginRight: 15,
  },
  statsTitle: {
    fontFamily: "Inter-SemiBold",
    fontSize: 20,
    color: COLORS.black,
  },
  statsSummary: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
    gap: 4,
  },
  statsBox: {
    borderWidth: 1,
    borderColor: COLORS.gray4,
    borderRadius: 10,
    flex: 1,
    alignItems: "center",
    paddingVertical: 15,
    gap: 5,
  },
  statsBoxValue: {
    fontSize: 20,
    fontFamily: "Inter-SemiBold",
    color: COLORS.black,
  },
  statsBoxLabel: {
    fontSize: 13,
    fontFamily: "Inter-Regular",
    color: COLORS.black,
    textAlign: "center",
  },
  statsSubtitle: {
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
    marginBottom: 8,
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  statsLabel: {
    width: 110,
    fontSize: 14,
    fontFamily: "Inter-Regular",
    color: COLORS.black,
  },
  statsProgressWrapper: {
    width: 100,
    // flexBasis: 10,
    height: 16,
    backgroundColor: COLORS.gray5,
    borderRadius: 10,
    overflow: "hidden",
    marginLeft: 50,
    marginRight: 12,
  },
  statsProgressBar: {
    height: "100%",
    backgroundColor: COLORS.primary,
    borderRadius: 6,
  },
  statsStatus: {
    flex: 0.5,
    fontSize: 13,
    fontFamily: "Inter-Regular",
    color: "#000",
  },

  // future health
  futureCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    marginVertical: 12,
  },
  futureTitle: {
    fontFamily: "Inter-SemiBold",
    fontSize: 16,
    color: COLORS.black,
  },
  futureSubtitle: {
    fontFamily: "Inter-Regular",
    fontSize: 14,
    color: COLORS.black,
    marginBottom: 16,
  },
  futureRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  futureLabel: {
    fontFamily: "Inter-Medium",
    fontSize: 14,
    color: COLORS.black,
  },
  futureBadge: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 30,
  },
  futureBadgeText: {
    fontFamily: "Inter-Medium",
    fontSize: 14,
    color: COLORS.black,
  },
  futureBadgeWarning: {
    borderColor: COLORS.yellow2nd,
    backgroundColor: COLORS.white,
  },
  futureBadgeTextWarning: {
    color: COLORS.black,
  },
  recommendBox: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    marginTop: 10,
    backgroundColor: COLORS.primary5th,
    padding: 14,
  },
  recommendTitle: {
    fontFamily: "Inter-SemiBold",
    fontSize: 14,
    marginBottom: 6,
    color: COLORS.black,
  },
  recommendItem: {
    fontFamily: "Inter-Regular",
    fontSize: 13,
    color: COLORS.black,
    marginBottom: 4,
  },
  barContainer: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 10,
    paddingVertical: 15,
    marginBottom: 5,
    borderColor: COLORS.gray4,
    zIndex: 100,
    borderWidth: 1,
    borderRadius: 10,
  },
  bsTitle: {
    flexDirection: "row",
    gap: 4,
  },
  barTitle: {
    fontSize: 12,
    fontFamily: "Inter-Medium",
    marginBottom: 8,
  },
  barNumber: {
    fontSize: 16,
    fontFamily: "Inter-SemiBold",
    marginBottom: 16,
  },
  barSatuan: {
    fontSize: 16,
    fontFamily: "Inter-Medium",
    marginBottom: 16,
    color: COLORS.gray1,
  },
  highestText: {
    fontSize: 10,
    color: COLORS.gray1,
  },
  highestDay: {
    fontSize: 12,
    color: COLORS.black,
    marginTop: 2,
  },
  bpContainer: {
    padding: 10,
    marginBottom: 16,
    borderColor: COLORS.gray4,
    zIndex: 100,
    borderWidth: 1,
    marginHorizontal: 10,
    borderRadius: 10,
  },
  bpTitle: {
    fontSize: 12,
    fontFamily: "Inter-Medium",
    color: COLORS.gray1,
    marginBottom: 5,
    paddingTop: 15,
  },
  bpInnerContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  bpStatus: {
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 5,
    marginLeft: 8,
  },

  statsContainer: {
    backgroundColor: "white",
    borderRadius: 10,
    padding: 16,
    marginRight: 0,
  },

  subStatContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 4,
  },
  halfChart: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: 12,
  },
  textContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
  },
  textToday: { fontSize: 12, fontFamily: "Inter-Medium" },
  textNum: { fontSize: 16, fontFamily: "Inter-Semibold" },
  borderChart: {
    borderColor: COLORS.gray3,
    borderWidth: 1,
    borderRadius: 10,
    padding: 4,
    marginTop: 10,
    backgroundColor: COLORS.white,
  },
});
