import { COLORS } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalView: {
    width: "85%",
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  closeButton: {
    position: "absolute",
    top: 15,
    right: 15,
    padding: 8,
    zIndex: 1,
  },
  closeButtonText: {
    fontSize: 20,
    color: "black",
    fontWeight: "400",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
    marginTop: 5,
    textAlign: "center",
    color: "black",
  },
  iconContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  iconCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: COLORS.secondary,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  categoryImage: {
    width: 36,
    height: 36,
  },
  iconLabel: {
    fontSize: 15,
    color: "black",
    fontWeight: "500",
  },
  card: {
    backgroundColor: COLORS.secondary5th,
    borderRadius: 12,
    padding: 16,
    width: "100%",
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 13,
    color: COLORS.gray2,
    marginBottom: 8,
    fontWeight: "400",
  },
  cardContent: {
    fontSize: 15,
    color: "black",
    lineHeight: 20,
    marginBottom: 12,
    fontWeight: "400",
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    width: "100%",
    marginBottom: 12,
  },
  infoBox: {
    flex: 1,
    backgroundColor: COLORS.secondary5th,
    borderRadius: 8,
    padding: 12,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 70,
  },
  infoIcon: {
    width: 20,
    height: 20,
    marginBottom: 6,
  },
  infoText: {
    fontSize: 13,
    color: "black",
    fontWeight: "500",
    textAlign: "center",
  },
  timeBubble: {
    backgroundColor: COLORS.secondary5th,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
  },
  clockIcon: {
    width: 18,
    height: 18,
  },
  timeText: {
    fontSize: 15,
    color: "black",
    fontWeight: "500",
  },
  markAsDoneButton: {
    backgroundColor: "black",
    padding: 16,
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
    marginTop: 8,
  },
  markAsDoneButtonText: {
    color: "white",
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  editReminderButton: {
    backgroundColor: "white",
    padding: 16,
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
    marginTop: 12,
    borderWidth: 1.5,
    borderColor: "black",
  },
  editReminderButtonText: {
    color: "black",
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
});
