import { COLORS } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background2nd,
  },
  headerContainer: {
    width: "100%",
    backgroundColor: COLORS.background2nd,
  },
  dashboardContainerLinear: {
    flex: 1,
    paddingHorizontal: 20,
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "70%",
  },
  scrollView: {
    position: "absolute",
    top: 90,
    left: 0,
    right: 0,
    bottom: 0,
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingBottom: 200,
    paddingHorizontal: 16,
  },
  keyboardAvoid: {
    flex: 1,
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 0,
    zIndex: 1,
    height: 80,
    paddingTop: 50,
    marginBottom: 37,
  },
  backButton: {
    padding: 8,
    borderRadius: 8,
  },
  backIcon: {
    width: 24,
    height: 24,
    resizeMode: "contain",
  },
  headerTitle: {
    fontSize: 24,
    color: COLORS.black,
    fontFamily: "Inter-Semibold",
  },
  headerSpacer: {
    width: 40,
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    paddingHorizontal: 20,
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    paddingVertical: 35,
  },
  titleInput: {
    fontSize: 16,
    fontFamily: "Inter-Medium",
    color: COLORS.black,
    borderWidth: 1,
    borderColor: COLORS.gray2,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 15,
  },
  separator: {
    height: 1,
    backgroundColor: COLORS.gray4,
    marginVertical: 10,
  },
  section: {
    marginBottom: 10,
  },
  label: {
    fontSize: 16,
    color: COLORS.black,
    marginBottom: 8,
    fontFamily: "Inter-Medium",
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.black,
    marginBottom: 8,
    fontFamily: "Inter-Medium",
  },
  dobWrapper: {
    width: "100%",
    position: "relative",
  },
  inputField: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.gray2,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: COLORS.white,
  },
  inputText: {
    fontSize: 14,
    color: COLORS.black,
    flex: 1,
  },
  placeholderText: {
    color: COLORS.gray2,
  },
  buttonContainer: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
  },
  chevronIcon: {
    marginLeft: 8,
  },
  deleteButton: {
    backgroundColor: COLORS.red,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 12,
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  deleteButtonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "600",
  },
  submitButton: {
    backgroundColor: COLORS.primary3rd,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 12,
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  submitButtonSmall: {
    flex: 2,
  },
  submitButtonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "600",
  },
  descriptionContainer: {
    borderWidth: 1,
    borderColor: COLORS.gray2,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: 80,
  },
  descriptionInput: {
    fontSize: 14,
    color: COLORS.black,
    textAlignVertical: "top",
    minHeight: 60,
    borderRadius: 10,
  },
  titleHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
    gap: 10,
  },
});
