import { COLORS } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalView: {
    width: "85%",
    backgroundColor: "white",
    borderRadius: 20,
    padding: 25,
    alignItems: "center",
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  closeButton: {
    position: "absolute",
    top: 15,
    right: 15,
    padding: 8,
    zIndex: 1,
  },
  closeButtonText: {
    fontSize: 20,
    color: "black",
    fontWeight: "bold",
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 20,
    marginTop: 10,
    textAlign: "center",
    color: "black",
  },
  iconContainer: {
    alignItems: "center",
    marginBottom: 25,
  },
  iconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#1A73E8",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  categoryImage: {
    width: 40,
    height: 40,
  },
  iconLabel: {
    fontSize: 16,
    color: COLORS.black,
    fontWeight: "600",
  },
  card: {
    backgroundColor: COLORS.primary5th,
    borderRadius: 12,
    padding: 16,
    width: "100%",
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary5th,
  },
  cardTitle: {
    fontSize: 14,
    color: COLORS.gray2,
    marginBottom: 8,
    fontWeight: "600",
  },
  cardContent: {
    fontSize: 16,
    color: "black",
    lineHeight: 22,
  },
  timeContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  timeBubble: {
    backgroundColor: COLORS.primary5th,
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: COLORS.primary5th,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  clockIcon: {
    width: 14,
    height: 14,
  },
  timeText: {
    fontSize: 14,
    color: "black",
    fontWeight: "500",
  },
  repeatDaysContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  dayBubble: {
    backgroundColor: COLORS.primary3rd,
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: COLORS.primary3rd,
  },
  dayText: {
    fontSize: 12,
    color: COLORS.primary5th,
    fontWeight: "500",
  },
  markAsDoneButton: {
    backgroundColor: "black",
    padding: 16,
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
    marginTop: 8,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  markAsDoneButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
  },
  editReminderButton: {
    backgroundColor: "white",
    padding: 16,
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
    marginTop: 12,
    borderWidth: 2,
    borderColor: "black",
  },
  editReminderButtonText: {
    color: "black",
    fontSize: 16,
    fontWeight: "600",
  },
});
