import { COLORS } from "@/constants/colors";
import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.primary,
  },
  dashboardContainerLinear: {
    flex: 1,
    paddingHorizontal: 20,
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "70%",
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
    paddingBottom: 30,
  },
  header: {
    backgroundColor: COLORS.primary,
    paddingTop: 50,
    paddingHorizontal: 25,
    paddingBottom: 30,
    alignItems: "center",
    minHeight: height * 0.3,
    justifyContent: "center",
  },
  logo: {
    width: 35,
    height: 35,
    marginBottom: 20,
    tintColor: COLORS.white,
    alignSelf: "center",
  },
  title: {
    fontSize: width < 375 ? 28 : 32,
    fontWeight: "bold",
    color: COLORS.white,
    marginBottom: 20,
    textAlign: "center",
    width: "100%",
    lineHeight: 38,
  },
  progressBarContainer: {
    width: "100%",
    alignItems: "center",
    marginBottom: 30,
    paddingHorizontal: 20,
  },
  progressBar: {
    height: 8,
    width: "80%",
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: COLORS.white,
    borderRadius: 4,
    width: "80%",
  },
  formWrapper: {
    alignItems: "center",
    width: "100%",
  },
  formContainer: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 20,
    paddingVertical: 24,
    width: width - 40,
    marginHorizontal: 20,
    borderRadius: 12,
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.black,
    textAlign: "left",
  },
  underline: {
    height: 0.1,
    backgroundColor: COLORS.gray1,
    width: "100%",
    marginTop: 12,
    marginBottom: 12,
  },
  label: {
    alignSelf: "flex-start",
    fontSize: 14,
    color: COLORS.black,
    marginBottom: 5,
    fontWeight: "500",
  },
  required: {
    color: COLORS.red,
  },
  dropdownWrapper: {
    width: "100%",
    marginBottom: 15,
  },
  dropdownButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.gray1,
    paddingHorizontal: 10,
    paddingVertical: 12,
    minHeight: 48,
    borderRadius: 8,
  },
  dropdownButtonActive: {
    borderColor: COLORS.primary,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  dropdownText: {
    fontSize: 15,
    color: COLORS.black,
  },
  placeholderText: {
    color: COLORS.black,
  },
  dropdownMenu: {
    marginTop: 6,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.gray1,
    borderRadius: 8,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  dropdownScroll: {
    maxHeight: 200,
  },
  dropdownOption: {
    paddingHorizontal: 10,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.primary5th,
  },
  dropdownOptionLast: {
    borderBottomWidth: 0,
  },
  dropdownOptionActive: {
    backgroundColor: COLORS.primary4th,
    borderRadius: 6,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  dropdownOptionText: {
    fontSize: 15,
    color: COLORS.black,
  },
  continueButton: {
    backgroundColor: COLORS.black,
    paddingVertical: 14,
    borderRadius: 6,
    alignItems: "center",
    marginTop: 20,
    marginBottom: 16,
    width: "100%",
  },
  continueText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: "600",
  },
  errorText: {
    color: COLORS.red,
    fontSize: 14,
    marginTop: 8,
    textAlign: "left",
  },
  backButton: {
    position: "absolute",
    left: 0,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    zIndex: 1,
    paddingLeft: 20,
    paddingTop: 80,
  },
  icon: {
    width: 24,
    height: 24,
    resizeMode: "contain",
  },
});
