import { COLORS } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  dashboardContainerLinear: {
    flex: 1,
    paddingHorizontal: 20,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 100,
  },
  header: {
    paddingTop: 40,
    paddingBottom: 18,
    alignItems: "flex-start",
    marginLeft: 35,
  },
  logo: {
    width: 35,
    height: 35,
    marginBottom: 14,
    tintColor: COLORS.white,
    alignSelf: "flex-start",
  },
  title: {
    fontSize: 32,
    color: COLORS.white,
    marginBottom: 6,
    textAlign: "left",
    width: "100%",
    fontFamily: "Inter-Semibold",
  },
  subtitle: {
    fontSize: 16,
    color: "rgba(255, 255, 255, 0.85)",
    textAlign: "left",
    lineHeight: 20,
    width: "100%",
    fontFamily: "Inter-Regular",
  },
  formWrapper: {
    width: "100%",
    alignItems: "center",
    paddingBottom: 40,
  },
  formContainer: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 18,
    paddingVertical: 18,
    width: "90%",
    alignSelf: "center",
    borderRadius: 10,
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 10,
  },
  bottomContainer: {
    width: "90%",
    alignItems: "center",
    marginTop: 10,
    alignSelf: "center",
    marginBottom: 20,
  },
  label: {
    alignSelf: "flex-start",
    fontSize: 16,
    color: COLORS.black,
    marginBottom: 5,
    fontWeight: "500",
  },
  required: {
    color: COLORS.red,
  },
  dobWrapper: {
    width: "100%",
    position: "relative",
    marginBottom: 15,
  },
  calendarIcon: {
    position: "absolute",
    right: 12,
    top: 36,
    zIndex: 1,
  },
  genderContainer: {
    flexDirection: "row",
    marginTop: 6,
    marginBottom: 12,
    width: "100%",
  },
  genderOption: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 30,
  },
  radioButton: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: "#D0D0D0",
    marginRight: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  radioButtonSelected: {
    borderColor: COLORS.black,
  },
  radioButtonInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.black,
  },
  genderText: {
    fontSize: 14,
    color: COLORS.black,
  },
  continueButton: {
    backgroundColor: COLORS.black,
    paddingVertical: 14,
    borderRadius: 6,
    alignItems: "center",
    marginTop: 24,
    marginBottom: 16,
    width: "100%",
  },
  continueText: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: "Inter-regular",
  },
  loginText: {
    textAlign: "center",
    fontSize: 14,
    color: COLORS.gray1,
    marginBottom: 10,
    width: "100%",
  },
  loginLink: {
    color: COLORS.primary,
    fontFamily: "Inter-Medium",
  },
  dividerContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 16,
    width: "100%",
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: COLORS.white,
  },
  dividerText: {
    marginHorizontal: 12,
    fontSize: 14,
    color: COLORS.white,
  },
  googleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.white,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.secondary4th,
    marginBottom: 16,
    width: "100%",
  },
  googleIcon: {
    width: 18,
    height: 18,
    marginRight: 18,
  },
  googleText: {
    fontSize: 15,
    color: COLORS.black,
    fontWeight: "500",
  },
  errorText: {
    color: COLORS.red,
    fontSize: 12,
    marginTop: 2,
    marginBottom: 4,
  },
});
